import Head from 'next/head'

const HeadSeo = ({
  title = 'Create Next App',
  content = 'Generated by create next app',
  faviconUrl = '/favicon.ico',
}) => {
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content={content} />
      <link rel="icon" href={faviconUrl} />
    </Head>
  )
}

export default HeadSeo
